version: '3'

services:

  webapp:
    build: ./php
    volumes:
      - ./php:/var/www/html
    env_file:
      - ".env"
    environment:
      - "PAYMENT_API"
#    links:
#      - payment
    ports:
      - "8000:8000"
